service: serverless-image-processing

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::sls-demos-bucket-102"

functions:
  uploadFile:
    handler: handler.uploadFile
    events:
      - http:
          path: uploadFile
          method: post
          cors: true

  processImage:
    handler: handler.processImage
    events:
        - s3:
            bucket: sls-demos-bucket-102
            event: s3:ObjectCreated:*
