service: serverless-image-processing

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    BUCKET: ${file(./config.yml):BUCKET}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::sls-demos-bucket-103"

functions:
  uploadFile:
    handler: lib/functions/uploadFile.handler
    events:
      - http:
          path: uploadFile
          method: post
          cors: true

  processImage:
    handler: lib/functions/processImage.handler
    events:
        - s3:
            bucket: sls-demos-bucket-103
            event: s3:ObjectCreated:*
